### ISSUE TITLE
Expansion for the calculator: Extend theorycrafting with the possibility to switch gear pieces, active skill gems and support gems, and possibly number of active charges

### ISSUE THREAD

**Issue by PrutsendePrutser** [PoESkillTree/PoESkillTree#100]
Hey there, I've been having the idea for quite a while to make a dps calculator for path of exile, where you can also play around with your main skill gems, support gems and gear. I often find myself having a hard time to decide if item x on poe.trade is worth my y amount of currency for the gain that it gives me, or finding the most optimal skillgem combinations for my gearset + tree

I've seen in issue #42 that you already discussed something about adding this functionality to the skilltree calculator. Are there still plans to do this, and if so, do you need help with implementing it?

**Comment by SpaceOgre** [comment]
To my knowledge no one have started any work on this, so if you feel up to it please dig in!

**Comment by Deathangel908** [comment]
I also would like to see frenzy charges + auras + flask charges. Didn't find anything implemented here. gonna take a look at source and see what I can add.

**Comment by brather1ng** [comment]
Would be great to have!

Someone started (and abandoned) working on aura stuff over a year ago (#107). Maybe you can get ideas from what he did.

**Comment by PrutsendePrutser** [comment]
Didn't respond to the initial comment by @SpaceOgre, because work got really busy at that point. I might take a look at it tomorrow/during the weekend (even though the PoE update launches on friday), If there isn't any work done yet on this issue, I'll try to pick it up. I remember that something was added a while ago, that shows maximum dps, defensive stats etcetera, but as @Deathangel908 stated, there wasn't any support for activating/deactivating aura's, nor was there the option to swap skill gems around (even if it's only the support gems)

**Comment by EmmittJ** [comment]
Yep, the calculation system is pretty much built, but it will need to be
expanded a bit for auras and such. All the gems and stats are pulled for
you and are located in items.xml (I think).

**Comment by l0g0sys** [comment]
Well, all you have to do, to get your auras and buffs into calculation of offensive/defensive stats is
add third argument to Compute.Initialize():
```
// Initializes structures.
public static void Initialize(SkillTree skillTree, ItemAttributes itemAttrs, AttributeSet buffAttrs)
```
and add them to Global working attribute set in method definition:
```
 ...
 Global.Add(Equipment);

+Global.Add(buffAttrs);

 CoreAttributes();
 ...
```
From then you can do whatever you want with auras and buffs, and all you have to do is just keep buffAttrs filled with attributes from active auras/buffs and that's it.
