### ISSUE TITLE
[Jewel Sockets] Sum Stats in area

### ISSUE THREAD

**Issue by EmmittJ** [PoESkillTree/PoESkillTree#163]
I was thinking that it would be nice to be able to hover over a jewel and maybe press a modifier and it will give you a summation of the stats within small, medium, and large radii. 

We will have to do this in the future anyway for full jewel support, so I thought it would be a good start. What do you guys think?

@l0g0sys @SpaceOgre

**Comment by l0g0sys** [comment]
Yeah, skill node lookup function for jewel AoE regions will be needed for sure.
So why not start with this.

**Comment by SpaceOgre** [comment]
I see no reason not to start with this, we will need it sooner or later.

**Comment by SpaceOgre** [comment]
Something like we already do to see if we hover over a point should work, with some tweaks.
Change 50 to radius size and done more or less. 
```
Point p = ((MouseEventArgs)e.OriginalSource).GetPosition(zbSkillTreeBackground.Child);
var v = new Vector2D(p.X, p.Y);

v = v * _multransform + _addtransform;

IEnumerable<KeyValuePair<ushort, SkillNode>> nodes =
	SkillTree.Skillnodes.Where(n => ((n.Value.Position - v).Length < 50)).ToList();
```

**Comment by EmmittJ** [comment]
Yeah, I was thinking we should be able to use the jewel socket position and get what is in range. I actually had remembered that little piece of code and thought we could change it up. 

We can easily turn this into a method to get what is in range for a specified size

**Comment by EmmittJ** [comment]
![Eww](http://i.imgur.com/veZrJY5.png)
I am not sure this is going to be a good way tot display these...

**Comment by SpaceOgre** [comment]
Yeah, that wont work. Three columns might be better but I still think it will be to much data for a tooltip. Another way could be to open a popup window and there show three columns. Here we could also give the user the possibility to filter the result since usually the jewels only interact with one type of stat, eg. dex.

**Comment by EmmittJ** [comment]
I was thinking a whole new window where it would display the stats within
the each radius as well as socketing the jewels

**Comment by SpaceOgre** [comment]
It would also be nice to be able to see the summation of all the selected nodes, not just all nodes, so you can easier see what a jewel will do for your current build.

**Comment by EmmittJ** [comment]
Yep, just need to figure out a ui design that would look good. I was
thinking something similar to how the main app is laid out. Summary of
stats both skilled and all on the left hand side, then maybe a unique jewel
system on the right side adding support for magic/rare jewels later.

**Comment by SpaceOgre** [comment]
Would be nice to have an interaction designer right about now ;)

**Comment by EmmittJ** [comment]
Know any? Haha

**Comment by Hixxie** [comment]
Display stats only if passive is allocated? That might clean up the clutter a little.
