### ISSUE TITLE
Intuitive leap support

### ISSUE THREAD

**Issue by Ruze** [PoESkillTree/PoESkillTree#214]
Any chance we could have the option to manually add nodes without pathing? I realise you can import a tree from the official site with jumps in pathing but there is no way to do this in this tool.

**Comment by ImaginaryDevelopment** [comment]
I'm trying to find my way around the code to see how to do this, is what `Jewel` is in a jewel socket something that is stored somewhere? Not sure how to use the UI to add it yet. If it is stored, would be in the `node.Attributes` dictionary? I've found my way to `zbSkillTreeBackground_MouseMove` as a place to start the check for if we are in range of a jewel socket, and if that socket has `Intuitive Leap` in it

**Comment by brather1ng** [comment]
Jewels aren't supported at all atm. You pretty much can't implement Intuitive Leap support right now (without implementing jewel support itself beforehand).
