### ISSUE TITLE
Skill tree generator popup window positioning

### ISSUE THREAD

**Issue by srmark** [PoESkillTree/PoESkillTree#461]
The popup window of skill tree gen can be dragged outside of the main window of the program, and if it's dragged out too much, it cannot be dragged back because the whole popup is outside. I have 2 screens and dragged that popup to the other screen, and I needed to restart the program to reset it's position to the default center.

**Comment by MLanghof** [comment]
What would you suggest as solution? We really wouldn't want to prevent people with two screens from making use of their screen estate...

**Comment by srmark** [comment]
Maybe you misunderstood me, or I had a bug you couldn't reproduce, but the problem is that when the popup is outside of the main window, it is clipped, like the css overflow hidden setting, overflowing part is invisible, and it can even be in a state when the whole popup is dragged out and invisible. I guess the solution would be to make it visible even when it is outside of the main window?

**Comment by brather1ng** [comment]
> I guess the solution would be to make it visible even when it is outside of the main window?

The popup is not a "real" window. It's only an overlay over the main window, so it can't be visible outside the main window. This is necessary for our dialog system (which also doesn't use real windows).

A solution would be to not allow it to be dragged completely outside the main window, but I think that is outside our control as the overlay/child window is from a library.

**Comment by srmark** [comment]
I see, yes, your second suggestion would be also good, but I didn't know your limitations, even if it's a won't fix, I think it qualifies as a bug.

**Comment by brather1ng** [comment]
I feel like this isn't worth fixing or investigating further. It should only happen once and then you know not to drag it completely out of the main window. And if it happens once in a while, you can just restart.

**Comment by yazilliclick** [comment]
This is fixed in current versions of the MahApps.Metro and MahApps.Metro.SimpleChildWindow.  It will now prevent dragging a window outside of it's parent.

**Comment by brather1ng** [comment]
Thanks, seems like an easy fix then.
