### ISSUE TITLE
Skill tree generator window missing.

### ISSUE THREAD

**Issue by ThrenodyFalls** [PoESkillTree/PoESkillTree#494]
i can't get it to show up at all. the generator will run, but only for tagged nodes.
delete/reinstall does not resolve this.
any ideas?

**Comment by MLanghof** [comment]
Hm, we had #461 a while ago but that should be fixed by program restarts already... Is this a new issue (has it worked before/in a different version)? Do old versions of the program have the same issue?

**Comment by ThrenodyFalls** [comment]
#461 i've had for a while, it's a nuisance, but restarting does resolve it.
this i'm seeing in every version since 2.4.1. generator window exists for me in 2.4.0 and earlier.
with the changes to the generator in 2.4.1 is there some new button to bring up the window that i'm just not finding?

**Comment by brather1ng** [comment]
Nodes -> Skill Tree Generator in the top menu is the button, but that was not changed since 2.4.0.

**Comment by ThrenodyFalls** [comment]
you're right, i mislabled 2.3.0 as 2.4.0. just checked the proper 2.4.0 and the bug is present for me.
every version since nodes was moved out of the tools menu and the generator info page was added has no generator window at all.

**Comment by brather1ng** [comment]
You can click on the "Advanced" in the top

![grafik](https://user-images.githubusercontent.com/7596346/29743654-9695757c-8a96-11e7-9d01-3f9fc8ce498c.png)

**Comment by ThrenodyFalls** [comment]
i had a feeling i was an idiot somehow. thanks for the help :)

**Comment by brather1ng** [comment]
No problem :)
