### ISSUE TITLE
New Version 2.7.4 Won't Autoupdate

### ISSUE THREAD

**Issue by dsnvwlmnt** [PoESkillTree/PoESkillTree#498]
I have 2.7.2 (standalone).

I click "Check for Updates".

Result: "You have the latest version!"

**Comment by dsnvwlmnt** [comment]
In the meantime, how would one go about overwriting 2.7.2, updating to 2.7.4 without breaking anything?

**Comment by EmmittJ** [comment]
You can download 2.7.4 and install it. It will install along side 2.7.2 since they are technically different programs. Your builds can be found by viewing your build save path in Edit > Settings

**Comment by dsnvwlmnt** [comment]
I have the non-installed 2.7.2 standalone version, and would like to use the non-installed standalone 2.7.4. Will it use the same build folder without breaking anything? I've had issues with this in the past and would like to ensure i won't again if i do this.

**Comment by EmmittJ** [comment]
You can download the 2.7.4 zip and copy over your build folder. It should be located where you unzipped 2.7.2
