### ISSUE TITLE
Check for Updates fails with SSL error

### ISSUE THREAD

**Issue by brather1ng** [PoESkillTree/PoESkillTree#503]
"The request was aborted: Could not create SSL/TLS secure channel."

Seems like GitHub changed another thing in their API

**Comment by Nhowka** [comment]
Paket had a problem with it recently, fixed with this code:

```C#
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12
                                         | SecurityProtocolType.Tls11
                                         | SecurityProtocolType.Tls
                                         | SecurityProtocolType.Ssl3;
```

You can check the discussion here: fsprojects/Paket/pull/3066
