### ISSUE TITLE
High CPU usage when dragging the tree around

### ISSUE THREAD

**Issue by RUSshy** [PoESkillTree/PoESkillTree#514]
Hi

When moving skilltree view CPU usage skyrocket

Path of Builder have same issue

Why no developers care about performance anymore nowadays ?

Suggestions:

- Generate static image of the tree and don't touch it

Since WPF sucks, i have another suggestion:

- Embed MonoGame/SharpDX/OpenTK to what ever, and use GPU for rendering the node

This isn't doing any intensive graphic stuff, why is that CPU usage so high ?

**Comment by EmmittJ** [comment]
This isn't really constructive. Could you provide some examples of things that cause the CPU to "skyrocket"? Moving the skill tree doesn't seem to do anything (nor should it). All of the images are statically rendered except the active layer which gets re-rendered when you skill/unskill a node. 

I have done a lot of benchmarking in the past, and the rendering process is pretty damn fast. Do you happen to have a GPU? WPF drawing does use the GPU.

**Comment by MLanghof** [comment]
> Generate static image of the tree and don't touch it

That's exactly what is done from our side.

> Embed MonoGame/SharpDX/OpenTK to what ever, and use GPU for rendering the node

That's exactly what WPF does.

**Comment by RUSshy** [comment]
![test4](https://user-images.githubusercontent.com/18348637/50096945-11f1ad80-0219-11e9-8969-63b603067191.gif)

Then how do  you explain this ?

**Comment by brather1ng** [comment]
I don't see the problem with high CPU usage for short periods when actively using the program. It might not be optimal, but it's not slowing down anything in the program and doesn't last long enough to have a noticeable effect outside of the program.
