### ISSUE TITLE
no "% increased spell damage" mod on weapons?

### ISSUE THREAD

**Issue by Wyncote** [PoESkillTree/PoESkillTree#525]
Hey, i think i mush be missing something. I'm new to PoESkillTree, looks pretty sweet, but i'm running into a small problem.

i'm trying to add a spell damage prefix to a sceptre or a staff. There's no "% increased spell damage" mod, just a spell damage node that includes increased mana, as far as i can see. Am i blind? is it missing?

**Comment by brather1ng** [comment]
For staffs and sceptres it's the sixth slider under "#% increased Cold Damage".

All prefixes/suffixes that can't appear together on an item are grouped together, which got extremely unintuitive over time. Improving that is already on my list.
