### ISSUE TITLE
With all charges Calculations ignore the Power and Frenzy charge from Swift Killer

### ISSUE THREAD

**Issue by Blakaraz** [PoESkillTree/PoESkillTree#526]
Title. With this tree (http://poeurl.com/cht3) I have 5 frenzy and power charges, including Swift Killer, but the Calculations for "with all charges" stats only uses 4 - It also says +4 Power charges, +4 frenzy charges, and +1 to maximum frenzy charges and maximum power charges.

**Comment by brather1ng** [comment]
From what I can tell, the charges from Swift Killer work correctly in computation.

The things displayed under the attributes expander on the left side are independent of calculations. The attributes expander does almost no processing of stats, including not splitting the maximum charge stat from Swift Killer.
