### ISSUE TITLE
missing path between ColdHearted Calculation and +10 Intelligence above it

### ISSUE THREAD

**Issue by lyonnel4** [PoESkillTree/PoESkillTree#527]
Hi.
The node Coldhearted Calculation (near shadow start) was linked to the +10 intelligence node just above it (the one mandatory to access Growth and Decay or Expeditious Munitions groups of nodes) in 3.5
and is not anymore in 3.6.

It may be only a change from 3.5 to 3.6 but I don't think GGG would remove a path.

**Comment by cboursnell** [comment]
The tree is loaded from the json from ggg. so if it's not in their data, it won't be in this skill tree. looks like they removed it. maybe they think triangles are ugly

**Comment by EmmittJ** [comment]
Yep, the json hasn't been edited at all, so if something has been removed or changed that is what is there.
