### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by PoESkillTreeCrash** [PoESkillTree/PoESkillTree#528]
Portable version (PoESkillTree-WarfortheAtlas-3.0.0-alpha.1.zip) crashes while loading. Debug.txt included.

[debug.txt](https://github.com/PoESkillTree/PoESkillTree/files/2936971/debug.txt)

**Comment by brather1ng** [comment]
There seems to be an issue with the russian translation. Until that's fixed you can either remove the folder Locale\ru in the portable installation folder or add `<Language>en-US</Language>` under `<Options>` in PersistentData.xml in the portable installation folder.

**Comment by PoESkillTreeCrash** [comment]
> There seems to be an issue with the russian translation. Until that's fixed you can either remove the folder Locale\ru in the portable installation folder or add `<Language>en-US</Language>` under `<Options>` in PersistentData.xml in the portable installation folder.

Thank you, both solutions works fine.
