### ISSUE TITLE
crash at start

### ISSUE THREAD

**Issue by joe-bauers** [PoESkillTree/PoESkillTree#535]
Crashes on start after loading assets. Tried both versions, portable and installed. PoESkillTree-WarfortheAtlas-3.0.0-alpha.4 works just fine.

[main.txt](https://github.com/PoESkillTree/PoESkillTree/files/3592133/main.txt)

**Comment by brather1ng** [comment]
Please try updating your .NET Framework. It should only require .NET Framework 4.6.2, but for some reason it doesn't always seem to be satisfied with that.

**Comment by joe-bauers** [comment]
Thank you for the quick answer. And that did it, so also thank you for the help.
