### ISSUE TITLE
PoB pastebin import

### ISSUE THREAD

**Issue by brather1ng** [PoESkillTree/PoESkillTree#544]
We should be able to import PoB pastebins.

**Comment by SpaceOgre** [comment]
I guess you might already have this on your radar but if we are going to support PoB pastebins then we should probably add support for multiple trees for a single build since PoB have that.

Maybe add it as a separate issue since it does not need pastebin support to work.

**Comment by brather1ng** [comment]
We decided at some point that our current build folder structure is enough multiple tree support. So the solution for importing a pastebin with multiple trees would be to create multiple builds in a new folder. Compared to multiple trees in a single build, this has the upside that you can also have different equipment and skills per tree.

I'm not sure how useful it would actually be. I guess if people want it, we can do it, but I wouldn't see it as important as the pastebin import.
