### ISSUE TITLE
Organize buttons from different UI elements into a single one

### ISSUE THREAD

**Issue by brather1ng** [PoESkillTree/PoESkillTree#547]
Currently, our functionality reachable through buttons is placed all over the place. Some is in the Saved Builds expander, some is in the Equipment tab and some doesn't even have buttons (Skill Tree Generator). This would get even worse with #543 and #544.

To improve discoverability of features, these buttons should all be organized into a single UI element that's always visible. The obvious solution here is either a simple icon bar or ribbon control, but I'm open to other ideas.

New Top Level Build/Folder are exceptions imo, they could just be moved to the top.

**Comment by SpaceOgre** [comment]
I like the idea of a ribbon control, since then bigger icons and text can be used. A simple icon bar would require the user to know the icons or hover over them to know what it does.

**Comment by EmmittJ** [comment]
I think a ribbon would be useful. I think the Skill Tree/Equipment/Computation tabs need to be a bit more prominent. Also, editing socketed gems is a bit painful right now since you have to go to the equipment tab and know to double click/right click an inventory item. It might be useful to split that functionality out from the items themselves since it is dependent on the equipment slot rather than the actual equipment. 

Replacing the attributes flyout with something that is more akin to the computation would be pretty good as well. We don't really need the 4 tabs in that flyout and the computation tab gives you the break down (might be nice to add a tooltip on the stats to show where they come from).

**Comment by brather1ng** [comment]
A ribbon control it'll be, then.

> Also, editing socketed gems is a bit painful right now since you have to go to the equipment tab and know to double click/right click an inventory item.

Yeah, I know.  It's already been bound to the equipment slots instead of the slotted items. But it still requires clicking somewhere you might not expect it. Shouldn't be difficult to put the current edit socketed gems controls plus a slot selector on the same level as the three tabs currently are. A summary of the gems per slot would also be nice there.

> Replacing the attributes flyout with something that is more akin to the computation would be pretty good as well. We don't really need the 4 tabs in that flyout and the computation tab gives you the break down (might be nice to add a tooltip on the stats to show where they come from).

That's something I already planned to do as part of #545. The flyout is also already down to a single tab (Passive Attribute), which would be replaced by a summary version of the computation tab.

**Comment by brather1ng** [comment]
I somehow thought MahApps has a ribbon control included, but there's the MahApps compatible [Fluent.Ribbon](https://github.com/fluentribbon/Fluent.Ribbon), so I'm gonna experiment with that.

**Comment by SpaceOgre** [comment]
That is what I found as well, it seems like there is a Ribbon controll from MS but could not find much about it or if it is ported to core.

**Comment by brather1ng** [comment]
I probably found the same (https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.ribbon.ribbon?view=netcore-3.1). From a quick look, it seems to be available for core, but it requires using its own RibbonWindow class, which makes it incompatible with MahApps and its MetroWindow class or at least requires restyling it.

**Comment by SpaceOgre** [comment]
Yeah that is the one, I think Fluent.Ribbon is the way to go. At least the first thing to try.
Are you planing to let the main content control which icons/text show up in the ribbon? or keep it static?

**Comment by brather1ng** [comment]
I don't really know yet, but I guess for most stuff it makes sense to always be shown. I have no idea where the Tree/Equipment/Computation selector will go, but having a contextual ribbon tab per one of those might be useful. E.g. only show "Take Screenshot of Skilled Nodes" when the tree is open.
