### ISSUE TITLE
unable to import characters

### ISSUE THREAD

**Issue by Masterwolf2050** [PoESkillTree/PoESkillTree#565]
currently having issues with importing my characters. I currently play on steam and get a failed character retrieval

**Comment by brather1ng** [comment]
It's working fine for me.

Can you provide more info on what you are trying to do and what error you are getting? If your characters are not public, you need to check the "Profile is private" box.

**Comment by Masterwolf2050** [comment]
actually I got the character now importing but having issues now with the stash imports I get *Error prasing null value line 2 position 2 

here is the link to my stash file is:
https://www.pathofexile.com/character-window/get-stash-items?tabs=1&tabIndex=0&realm=pc&league=Standard&accountName=LoneBlackfang

**Comment by brather1ng** [comment]
Looks like GGG changed something in their API. Will be fixed in next league's release.

**Comment by Masterwolf2050** [comment]
Thanks for the heads up
