### ISSUE TITLE
Windows 8 Touch Screen

### ISSUE THREAD

**Issue by QuickBASIC** [PoESkillTree/PoESkillTree#79]
The application is near impossible to use with a touchscreen. Would it be possible to have it recognize scrolling/zooming touch events. At the moment, on a touch screen you can't click and drag around the tree like you can with the mouse.

**Comment by MLanghof** [comment]
I'm working on a surface, so I can maybe even help with not only the touch-support but also the pen inputs.

**Comment by MLanghof** [comment]
Touch support has been added with c2beb4b.
